name: Build

on:
  workflow_dispatch:

  push:
    tags:
      - 'v*'

jobs:

  build_browser_extensions:
    name: Build browser extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build_browser_extensions

      - name: upload chrome extension
        uses: actions/upload-artifact@v3
        with:
          path: artifacts/*.zip

  publish:
    name: Publish release
    needs:
      - build_browser_extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: martinbeentjes/npm-get-version-action@v1.3.1
        id: package-version

      - uses: actions/download-artifact@v3
        with:
          path: github-artifacts

      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: true
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          artifacts: github-artifacts/artifact/*
          body: |
            *This is a beta version. The browser addons are not updated yet, and the `:latest` tag of the docker image still points to the previous stable version.*
            ## Using elasticvue
            This version of elasticvue supports elasticsearch `8.x`, `7.x` and `6.8`.
            ### Browser extension
            * [Google Chrome](https://chrome.google.com/webstore/detail/elasticvue/hkedbapjpblbodpgbajblpnlpenaebaa)
            * [Mozilla Firefox](https://addons.mozilla.org/en-US/firefox/addon/elasticvue/)
            * [Microsoft Edge](https://microsoftedge.microsoft.com/addons/detail/elasticvue/geifniocjfnfilcbeloeidajlfmhdlgo)
